### ISSUE TITLE
Filelist Management and Auto-generation

### ISSUE THREAD

**Issue by xfguo** [jlsemi/scratchip#1]
### Checklist

- [x] Did you write out a description of the feature you want to see?
- [x] Did you look around for any related features?
- [x] Did you specify relevant external information?

Request a feature? Please fill out the sections below. 👍

### Feature Description

`project.yml` should always be created when we run `scratchip create PROJ`, the project.yml should include everything for re-init the project. Also, a version should be specified to make it's easy to upgrade to new version. 

```
# contents of project.yml
version: 0.2.1
filelist:
  rtl:
    - include 
    - rtl/verilog/ethmac.v
    - rtl/verilog/eth_clkgen.v
  sim:
    - inlucde: rtl
  syn:
    - include: rtl
  fpga:
    - include: rtl
```

1. support include other filelist
2. scratchip command to generate filelist with arguments, `scratchip filelist`
3. support include/include_dir
4. all filelist should be in pre-defined order

### Additional context

**Impact**: unknown

**Development Phase**: proposal

**Comment by colin4124** [comment]
### Configure 

`project.yml`
```yaml
filelist:
   rtl:
     defines:
       - FOO: 59
       - BAR
     files:
       - rtl/verilog/defines.v : is_include_file
       - rtl/verilog/subdir : is_include_dir
       - rtl/verilog/ethmac.v
       - rtl/verilog/eth_crc.v
     includes:
       - cpu.yml
       - an.yml
   sim:
     filesets: [rtl]
     files:
       - rtl/verilog/sim_defines.v : is_include_file
       - rtl/verilog/sim_rtl.v
   fpga:
     filesets: [sim]
     files:
       - rtl/verilog/fpga_defines.v : is_include_file
       - rtl/verilog/fpga.v

```
`cpu.yml`
```yaml
defines:
  - CORES: 59
  - CACHE
files:
  - rtl/cpu/defines.v : is_include_file
  - rtl/cpu/subdir : is_include_dir
  - rtl/cpu/core.v
```
`an.yml`
```yaml
defines:
  - AN_DELAY: 24
  - MDIO
files:
  - rtl/an/defines.v : is_include_file
  - rtl/an/subdir : is_include_dir
  - rtl/an/an.v
```

`rtl`, `sim` and `fpga` are targets. In a target, `files` is a list of path of verilog file; `includes` is other `yaml` filelist. `filesets` include other targets.

`includes` 's YAML should contain `defines` or `files` or both fields, such as:

```yaml
defines:
  - CORES: 59
  - CACHE
files:
  - rtl/cpu/defines.v : is_include_file
  - rtl/cpu/subdir : is_include_dir
  - rtl/cpu/core.v
```

### Usage

`scratchip filelist` would use default path 'PROJECT_ROOT/project.yml' to generate all tagets's filelist:

- `builds/filelist/rtl.f`
- `builds/filelist/sim.f`
- `builds/filelist/fpga.f`

`scratchip filelist path/to/your/project_cfg.yml -t [target]` would generate `[target]` 's filelist only. such as: `scratchip filelist myproject.yml -t rtl`

All filelist woulde be in pre-defined order.
